admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

