services:
    app.service.certificationy:
      class: AppBundle\Service\Certificationy\Client

#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
